In [2]:
import pandas as pd
import numpy as np

### Series as generalized NumPy array

In [3]:
#Explicit indexes, major difference between numpy array and pandas seriesAz
data = pd.Series([0.5, 1, 1.5, 2], index = ['a', 'b', 'c', 'd'])
data

a    0.5
b    1.0
c    1.5
d    2.0
dtype: float64

In [4]:
data.values

array([0.5, 1. , 1.5, 2. ])

In [5]:
#pd.Index is an array in itself 
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
data[1]

1.0

In [7]:
#Doesnt include data[1]
data[1:3]

b    1.0
c    1.5
dtype: float64

### Constructing Series objects

In [8]:
# Constructing without index

data = pd.Series([1, 2, 3])
data

0    1
1    2
2    3
dtype: int64

In [9]:
# Constructing scaler index
data = pd.Series(5, index = [10, 20, 30])
data

10    5
20    5
30    5
dtype: int64

In [10]:
# default index sorted to dictionary

data = pd.Series({10:'a',20:'b',30:'c'})
data

10    a
20    b
30    c
dtype: object

In [11]:
# preferred indexes

data = pd.Series({10:'a', 20:'b', 30:'c'}, index=[10, 30])
data

10    a
30    c
dtype: object

### Data Indexing and Selection

In [12]:
data =  pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['b']

0.5

In [14]:
'a' in data

True

In [15]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [16]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [17]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Selection - Series as one dimensional array 

In [18]:
#Slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [19]:
#data by implicit integer index
data[1:4]

b    0.50
c    0.75
d    1.00
dtype: float64

In [20]:
#masking
data[(data>0.3) & (data<0.8)]

b    0.50
c    0.75
dtype: float64

In [21]:
#fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

#### Indexers: loc, iloc and ix

In [22]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [23]:
#explicit index when indexing
data[1]

'a'

In [24]:
#implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

##### loc always indexing and slicing that references the explicit index

In [25]:
data.loc[1]

'a'

In [26]:
data.loc[1:3]

1    a
3    b
dtype: object

#### iloc always references implicit python style indexing 

In [27]:
data.iloc[1]

'b'

In [28]:
data.iloc[1:3]

3    b
5    c
dtype: object

### Data Selection in DataFrame

#### Data Selection - DataFrame as a dictionary

In [29]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297,
                 'Florida': 170312, 'Illinious': 149995})
pop = pd.Series({'California': 38334521, 'Texas': 26448193, 'New York': 19651127,
                 'Florida': 19552860, 'Illinious': 12882135})
data = pd.DataFrame({'area':area,'pop':pop} )
data

area       pop
California  423967  38334521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinious   149995  12882135

In [30]:
#accessing through dictionary-style indexing
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinious     149995
Name: area, dtype: int64

In [31]:
data['pop']

California    38334521
Texas         26448193
New York      19651127
Florida       19552860
Illinious     12882135
Name: pop, dtype: int64

In [32]:
#attribute style access
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinious     149995
Name: area, dtype: int64

In [33]:
#exactly the same
data.area is data['area']

True

In [34]:
data.pop is data['pop']

False

In [35]:
data.pop #dictionary indexing and attrribute style indexing will not be same if the 
#attributes are not string or are a function as pop is.

<bound method NDFrame.pop of               area       pop
California  423967  38334521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinious   149995  12882135>

In [36]:
data['Density'] = data['pop']/data['area']
data

area       pop     Density
California  423967  38334521   90.418643
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinious   149995  12882135   85.883763

#### DataFrame as two-dimensional array

In [37]:
data.values

array([[4.23967000e+05, 3.83345210e+07, 9.04186434e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [38]:
data.T

California         Texas      New York       Florida     Illinious
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833452e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
Density  9.041864e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [39]:
data.values[0]

array([4.23967000e+05, 3.83345210e+07, 9.04186434e+01])

In [40]:
data.iloc[:3, :2]

area       pop
California  423967  38334521
Texas       695662  26448193
New York    141297  19651127

In [41]:
data.loc[:'Illinious', :'pop']

area       pop
California  423967  38334521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinious   149995  12882135

In [42]:
data.ix[:3, :'pop']

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38334521
Texas       695662  26448193
New York    141297  19651127

In [43]:
#combining hybrid attribute style indexing and dictionary indexing
data.loc[data.Density>90, ['pop', 'Density']]

pop     Density
California  38334521   90.418643
New York    19651127  139.076746
Florida     19552860  114.806121

In [44]:
data.iloc[0, 2] = 90
data

area       pop     Density
California  423967  38334521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinious   149995  12882135   85.883763

In [45]:
#Indexing refers to columns and slicing refers to rows.

data['California':'Florida']

area       pop     Density
California  423967  38334521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121

In [46]:
data[1:3] #By default if we dont mention the columns and rows, it slices by rows

area       pop     Density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [47]:
data[data.Density>90] #masking is also is done row wise

area       pop     Density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

### Operating on Data in Pandas

In [48]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [49]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), 
                 columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [50]:
#Operations with indexes preserved
np.exp(ser) 

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [51]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [52]:
#Adjustment of indexes in cases of addition, replacing not available values with NAN
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [53]:
#if desired behaviour, is to fill values
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in DataFrame

In [54]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [55]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), 
                columns = list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [56]:
A + B #irrespective of their order inn the two objects, and indices in the result are sorted

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [57]:
A.add(B, fill_value=0)

A     B    C
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0

In [58]:
#filling up with mean values
fill = A.stack().mean()#finding column wise mean
A.add(B, fill_value=fill)


A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

#### Ufunc add(), sub(), mul(), div(), floor() [//] , mod(), pow() **

### Ufunc: Operations Between DataFrame and Series

In [59]:
A= rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [60]:
#Broadcasting row-wise
A-A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [61]:
df = pd.DataFrame(A, columns=list('QRST'))
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [62]:
df.sub(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [63]:
#Automatic alignment of rows
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [64]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Operating on Null Values

- isnull()
- notnull()
- dropna()
- fillna()

In [65]:
data = pd.Series([1, np.nan, 'hello', None])

In [67]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [69]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [70]:
data.dropna()

0        1
2    hello
dtype: object

In [74]:
df = pd.DataFrame([[1, np.nan, 2],
                 [2, 3, 5],
                 [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [76]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [77]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [79]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [80]:
df.dropna(axis='columns', how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [81]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

### Filling na values

In [83]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [84]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [85]:
#forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [87]:
#back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [88]:
    df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [90]:
df.fillna(method='bfill', axis=1)

0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN

### Combining Datasets: Concat and Append

In [92]:
#numpy concatenation
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
x=[[1,2],
  [3,4]]
np.concatenate([x,x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [100]:
#pandas.concat preserve indexes
ser1=pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2=pd.Series(['D', 'E', 'F'], index=[1,5,6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
1    D
5    E
6    F
dtype: object

### Catching the repeats as an error

In [102]:
try:
    pd.concat([ser1,ser2], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([1], dtype='int64')


In [103]:
print(ser1);print(ser2);print(pd.concat([ser1, ser2], ignore_index=True))

1    A
2    B
3    C
dtype: object
1    D
5    E
6    F
dtype: object
0    A
1    B
2    C
3    D
4    E
5    F
dtype: object


In [117]:
df5 = pd.DataFrame({'A': ['A1','A2'], 'B':['B1','B2'], 'C':['C1','C2']},index=[1,2])
df6 = pd.DataFrame({'B': ['B3','B4'], 'C':['C3','C4'], 'D':['D3','D4']},index=[3,4])
#df6 = pd.DataFrame([['B3','B4],[C3','C4'],['D3','D4']], columns=['B', 'C', 'D'])
print(df5); print(df6); print(pd.concat([df5,df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  after removing the cwd from sys.path.


In [118]:
print(df5); print(df6);

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4


In [119]:
print(pd.concat([df5, df6], join='inner'))

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [121]:
print(df5); print(df6);
print(pd.concat([df5, df6], join_axes=[df5.columns]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4


### The append method

In [122]:
print(df5);print(df6); print(df5.append(df6)); #this will create new object. 
#This is different than

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\core\frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)


## Combining Datasets: Merge and Join

### One to One joins

In [137]:
df1 = pd.DataFrame({'employee':['Bob', 'Jake', 'Lisa', 'Sue'],
                   'group':['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee':['Lisa', 'Bob', 'Jake', 'Sue'],
                   'hire_data':[2004, 2008, 2012, 2014]})
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_data
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [140]:
#pd.merge() function recognizes that each dataframe has an "employee" column and 
#automatically joins using the column as key
#merge also discards the indexes 
df3 = pd.merge(df1, df2)
df3

employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

### Many to-one joins

In [141]:
#Many to one -means one of the two key columns contain duplicate entries
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                   'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4); print(pd.merge(df3, df4))

  employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group  hire_data supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


### Many-to-many joins

#### Many to Many means both the dataframes has duplicate members

In [143]:
df5 = pd.DataFrame({'group':['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 
                             'HR'],
                   'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 
                              'orgaization']})
print(df1); print(df5); print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR   orgaization
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR   orgaization


### Specification of the Merge Key

#### The on keyword

In [145]:
print(df1); print(df2); print(pd.merge(df1, df2)); print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_data
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
  employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


### The left_on and right_on keywords

#### This is used to solve the problem of dataframes having different names

In [149]:
#The resultant has a redundant column
df3 = pd.DataFrame({'name':['Bob', 'Jake', 'Lisa', 'Sue'],
                   'salary':[70000, 80000, 120000, 90000]})
print(df1); print(df3);print(pd.merge(df1, df3, right_on='name', left_on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


In [152]:
print(df1); print(df3);print(pd.merge(df1, df3, right_on='name', left_on='employee').drop('name', axis=1))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000


### The left_index and right_index keywords

In [155]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a); print(df2a);

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_data
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


In [156]:
print(df1a); print(df2a);
print(pd.merge(df1a, df2a, left_index=True, right_index=True))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_data
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_data
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014
